## Switches
set_property PACKAGE_PIN V17 [get_ports {a}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {a}]
set_property PACKAGE_PIN V16 [get_ports {b}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {b}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {y_and}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y_and}]
set_property PACKAGE_PIN E19 [get_ports {y_or}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y_or}]
set_property PACKAGE_PIN U19 [get_ports {y_xor}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y_xor}]
set_property PACKAGE_PIN V19 [get_ports {y_not}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y_not}]
set_property PACKAGE_PIN W18 [get_ports {y_nand}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y_nand}]
set_property PACKAGE_PIN U15 [get_ports {y_nor}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y_nor}]
set_property PACKAGE_PIN U14 [get_ports {y_xnor}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {y_xnor}]
